# Generated by Django 5.1.14 on 2025-12-09 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novaterra', '0003_alter_location_options_location_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'verbose_name': 'Novaterra Camera', 'verbose_name_plural': 'Novaterra Cameras'},
        ),
        migrations.AlterField(
            model_name='camera',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novaterra_cameras', to='novaterra.location'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novaterra_cameras', to=settings.AUTH_USER_MODEL),
        ),
    ]
