# Generated by Django 5.1.14 on 2025-11-29 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novaterra', '0003_alter_location_options_location_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('symptoms', models.TextField()),
                ('treatment_steps', models.JSONField(help_text='List of treatment steps')),
                ('prevention_tips', models.JSONField(help_text='List of prevention tips')),
                ('organic_treatment', models.TextField(blank=True)),
                ('chemical_treatment', models.TextField(blank=True)),
                ('estimated_recovery_days', models.IntegerField(default=14)),
            ],
            options={
                'verbose_name': 'Treatment Recommendation',
                'verbose_name_plural': 'Treatment Recommendations',
                'ordering': ['disease_name'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=200)),
                ('confidence', models.FloatField(help_text='AI confidence score (0-1)')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('treating', 'Under Treatment'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='detected', max_length=20)),
                ('image', models.ImageField(upload_to='disease_detections/%Y/%m/%d/')),
                ('detection_date', models.DateTimeField(auto_now_add=True)),
                ('bbox', models.JSONField(blank=True, help_text='Bounding box coordinates [x1, y1, x2, y2]', null=True)),
                ('treatment_notes', models.TextField(blank=True)),
                ('treatment_date', models.DateTimeField(blank=True, null=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_detections', to='novaterra.field')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_detections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disease Detection',
                'verbose_name_plural': 'Disease Detections',
                'ordering': ['-detection_date'],
            },
        ),
    ]
